### PR TITLE
feature: da relay

### LINKED ISSUE #3: Implement a DA relay feature
- accept a list of additional DA servers from config or CLI
- when receiving data, will forward the data to the DA servers asynchronously
- if the forward fails, it may have a retry mechanism (with a configured number of retries)

### PR DESCRIPTION
**Pull request by blockchaindevsh**
Fixes https://github.com/ethstorage/da-server/issues/3

### CODE REVIEW

**Comment by pochenai** [comment]
To my understanding, there is a master server and some salve servers, right?

**Comment by blockchaindevsh** [comment]
> To my understanding, there is a master server and some salve servers, right?

Yeah kinda of, but it's a minimal version, much simpler than fully master-slave.

**Review by qzhodl — APPROVED** [review]

**Comment by qizhou** [comment]
> To my understanding, there is a master server and some salve servers, right?

Master/slave could be achieved by `op-conductor` in the sequencer cluster so the DA servers are just pure storage servers.

**Comment by qizhou** [comment]
I thinking whether we should introduce TTL to avoid the infinite relay issue.

**Comment by blockchaindevsh** [comment]
> I thinking whether we should introduce TTL to avoid the infinite relay issue.

When will the infinite relay issue happen?

**Comment by qizhou** [comment]
> > I thinking whether we should introduce TTL to avoid the infinite relay issue.
> 
> When will the infinite relay issue happen?

In a misconfigured network, if A relays to B, B relays to A, then we will have the infinite relay issue.

**Comment by qizhou** [comment]
One thing that help avoid the issue is that we require a sequencer IP / source IP, before relaying the data.

**Review by qizhou — APPROVED** [review]

**Comment by blockchaindevsh** [comment]
> One thing that help avoid the issue is that we require a sequencer IP / source IP, before relaying the data.

Yeah, it's white-listed.

**Pull request merged**
